id: I2C8E22BE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:52:20+00:00'
last_modified: '2022-06-08T08:04:20.192156+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25097
  title: ཟུར་མཁར་བློ་གྲོས་རྒྱལ་པོའི་གསུང་རྩོམ་གཅེས་བཏུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3A6C:
      image_group_id: I5681
      title: ''
      total_pages: 157
      order: 1
      base_file: 3A6C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
